apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gke
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-cont
        image: us-central1-docker.pkg.dev/civic-rhythm-404204/flask-cicd/flaskdemo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo
spec:
  selector:
    app: flask
  ports:
  - port: 5000
  type: LoadBalancer